<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>LinQ2Checker</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="4.7.0" />
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.34.0" />
  </ItemGroup>

  <Target Name="ILRepack" AfterTargets="Build" Condition="'$(Configuration)'=='Release'">
    <ItemGroup>
      <InputAssemblies Include="$(OutputPath)System.Management.dll" />
    </ItemGroup>
    <ILRepack
      ExePath="$(NuGetPackageRoot)ilrepack.lib.msbuild.task\2.0.34.0\tools\ILRepack.exe"
      Internalize="true"
      InputAssemblies="@(InputAssemblies)"
      MainAssembly="$(OutputPath)$(AssemblyName).exe"
      OutputFile="$(OutputPath)$(AssemblyName).exe"
    />
  </Target>
</Project>
